### ISSUE TITLE
Power Supply for Servo Motors

### ISSUE THREAD

**Issue by ahmedtalbi** [Wizer21/6Servo_Robot_Arm#1]
Nice Work! quick question which power supply are you using to power the servo motors?

**Comment by Wizer21** [comment]
The motors are plugged to this card :
https://www.amazon.fr/gp/product/B07V72VBJ4/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

That is powered with a pack of 4 batteries:
https://www.amazon.fr/DollaTek-Batterie-Holder-Wired-Cover/dp/B07DJ4S46F/ref=sr_1_19?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=boitier+piles+aa&qid=1620566649&sr=8-19

**Comment by ahmedtalbi** [comment]
Thanks a lot!
